"""
对话引擎 (Dialogue Engine)

Enhanced v0.6.0:
- Continuous Jaccard-based perspective distance and knowledge complementarity
- Dialogue depth tracking across repeated node pair interactions
- Cross-domain insight discovery
- Optional 8-dimension assessment bridge via dialogue_with_assessment()
"""

# # from __future__ import annotations  # Python 3.6 不支持  # Python 3.6 不支持

import json
import math
import re
from collections import defaultdict
from datetime import datetime
from typing import Any, Dict, List, Optional, Set, Tuple
from dataclasses import dataclass, field

from .node import Node


# ---------------------------------------------------------------------------
# DialogueResult dataclass
# ---------------------------------------------------------------------------

@dataclass
class DialogueResult:
    """对话结果 (Dialogue outcome)

    Attributes:
        dialogue_id: Unique identifier for this dialogue.
        participants: List of participant node IDs.
        input_context: Per-node context strings captured at dialogue time.
        emergence_score: Continuous emergence score in [0, 1].
        new_insight: Human-readable insight generated by the dialogue.
        new_world_state: Updated world state after the dialogue.
        treasure_unlocked: Treasure ID if emergence exceeded threshold.
        next_action: Suggested follow-up action.
        dimension_scores: Optional 8-dimension assessment scores factored
            into this dialogue (populated by ``dialogue_with_assessment``).
        cross_domain_insights: List of discovered cross-domain intersection
            descriptions (populated by ``_generate_insight``).
        timestamp: ISO-8601 timestamp of the dialogue.
    """

    dialogue_id: str
    participants: List[str]
    input_context: Dict[str, str]
    emergence_score: float
    new_insight: str
    new_world_state: Dict
    treasure_unlocked: Optional[str] = None
    next_action: str = "continue"
    dimension_scores: Optional[Dict[str, float]] = None
    cross_domain_insights: List[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> dict:
        """转换为字典"""
        return {
            "dialogue_id": self.dialogue_id,
            "participants": self.participants,
            "input_context": self.input_context,
            "emergence_score": self.emergence_score,
            "new_insight": self.new_insight,
            "new_world_state": self.new_world_state,
            "treasure_unlocked": self.treasure_unlocked,
            "next_action": self.next_action,
            "dimension_scores": self.dimension_scores,
            "cross_domain_insights": self.cross_domain_insights,
            "timestamp": self.timestamp,
        }

    def to_json(self) -> str:
        """转换为JSON字符串"""
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=2)


# ---------------------------------------------------------------------------
# Tokenization helpers (stdlib only)
# ---------------------------------------------------------------------------

# Pattern that splits on common Chinese and English delimiters while
# keeping meaningful tokens.
_WORD_SPLIT_RE = re.compile(
    r"[,;.!?\s，；。！？、\n\r\t/\\|()\[\]{}\"'`~@#$%^&*+=<>:：]+"
)


def _character_bigrams(text: str) -> Set[str]:
    """Extract character bigrams from *text*.

    >>> sorted(_character_bigrams("hello"))
    ['el', 'he', 'll', 'lo']
    """
    text = text.strip()
    if len(text) < 2:
        return {text} if text else set()
    return {text[i : i + 2] for i in range(len(text) - 1)}


def _word_tokens(text: str) -> Set[str]:
    """Split *text* on Chinese/English delimiters into word tokens.

    Empty strings are discarded.

    >>> sorted(_word_tokens("围棋, 人工智能; 策略"))
    ['人工智能', '围棋', '策略']
    """
    return {tok for tok in _WORD_SPLIT_RE.split(text) if tok}


def _jaccard_distance(set_a: Set[str], set_b: Set[str]) -> float:
    """Compute Jaccard *distance* (1 - similarity) between two sets.

    Returns 0.0 when both sets are empty (identical).
    """
    if not set_a and not set_b:
        return 0.0
    union = set_a | set_b
    if not union:
        return 0.0
    intersection = set_a & set_b
    return 1.0 - len(intersection) / len(union)


# ---------------------------------------------------------------------------
# DialogueEngine
# ---------------------------------------------------------------------------

class DialogueEngine:
    """对话引擎 (Dialogue Engine)

    Tracks dialogue history per node-pair to compute a *dialogue depth*
    multiplier that rewards sustained conversations between the same two
    nodes.

    Args:
        emergence_threshold: Emergence score above which a treasure is
            unlocked (default ``0.5``).
    """

    def __init__(self, emergence_threshold: float = 0.5) -> None:
        """
        初始化对话引擎

        Args:
            emergence_threshold: 涌现阈值，超过此值触发宝藏渲染
        """
        self.emergence_threshold = emergence_threshold
        self.dialogue_history: List[DialogueResult] = []
        # pair_key -> list of DialogueResult for that pair
        self._pair_history: Dict[Tuple[str, str], List[DialogueResult]] = defaultdict(list)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def dialogue(
        self,
        node_a: Node,
        node_b: Node,
        trigger: str = "",
    ) -> DialogueResult:
        """
        触发两个节点之间的对话

        Args:
            node_a: 节点A
            node_b: 节点B
            trigger: 触发事件描述

        Returns:
            DialogueResult: 对话结果
        """
        return self._run_dialogue(node_a, node_b, trigger)

    def dialogue_with_assessment(
        self,
        node_a: Node,
        node_b: Node,
        trigger: str = "",
        assessment_engine: Any = None,
    ) -> DialogueResult:
        """Run a dialogue optionally enriched with 8-dimension assessment data.

        When *assessment_engine* (an ``EightDimEngine`` instance) is provided
        and historical training records exist for either node, the resulting
        capability profiles are factored into the emergence calculation and
        stored in ``DialogueResult.dimension_scores``.

        Args:
            node_a: First participant node.
            node_b: Second participant node.
            trigger: Free-text description of the triggering event.
            assessment_engine: Optional ``EightDimEngine`` instance used to
                retrieve capability profiles for the participating nodes.

        Returns:
            DialogueResult enriched with ``dimension_scores`` when assessment
            data was available.
        """
        dim_scores: Optional[Dict[str, float]] = None
        assessment_boost: float = 0.0

        if assessment_engine is not None:
            profile_a = self._load_node_profile(assessment_engine, node_a.node_id)
            profile_b = self._load_node_profile(assessment_engine, node_b.node_id)

            if profile_a or profile_b:
                dim_scores = {}
                combined: Dict[str, List[float]] = defaultdict(list)
                for profile in (profile_a, profile_b):
                    if profile:
                        for dim, score in profile.items():
                            combined[dim].append(score)

                # Average across available profiles per dimension
                for dim, values in combined.items():
                    dim_scores[dim] = sum(values) / len(values)

                # Compute assessment boost: complementary strengths increase
                # emergence.  If A is strong where B is weak (and vice-versa)
                # the pair is more likely to produce emergent insights.
                if profile_a and profile_b:
                    complementarity = self._profile_complementarity(
                        profile_a, profile_b,
                    )
                    assessment_boost = complementarity * 0.15  # cap at 0.15

        result = self._run_dialogue(
            node_a, node_b, trigger,
            dimension_scores=dim_scores,
            assessment_boost=assessment_boost,
        )
        return result

    # ------------------------------------------------------------------
    # Core dialogue pipeline (shared by dialogue / dialogue_with_assessment)
    # ------------------------------------------------------------------

    def _run_dialogue(
        self,
        node_a: Node,
        node_b: Node,
        trigger: str,
        dimension_scores: Optional[Dict[str, float]] = None,
        assessment_boost: float = 0.0,
    ) -> DialogueResult:
        """Internal dialogue execution pipeline."""

        # 生成对话ID
        dialogue_id = f"dialogue-{datetime.now().strftime('%Y%m%d%H%M%S')}"

        # 收集输入上下文
        input_context = {
            node_a.node_id: f"视角: {node_a.seed['perspective']}, 知识: {node_a.seed['knowledge_base']}",
            node_b.node_id: f"视角: {node_b.seed['perspective']}, 知识: {node_b.seed['knowledge_base']}",
        }

        # 计算涌现值
        emergence_score = self._calculate_emergence(
            node_a, node_b, assessment_boost=assessment_boost,
        )

        # 生成新见解 & cross-domain insights
        new_insight, cross_domain_insights = self._generate_insight(
            node_a, node_b, emergence_score,
        )

        # 更新世界状态
        new_world_state = {
            "version": max(node_a.current_world["version"], node_b.current_world["version"]) + 1,
            "loaded_chunks": list(set(
                [c["chunk_id"] for c in node_a.current_world["loaded_chunks"]] +
                [c["chunk_id"] for c in node_b.current_world["loaded_chunks"]]
            )),
        }

        # 检查是否解锁宝藏
        treasure_unlocked = None
        if emergence_score > self.emergence_threshold:
            treasure_unlocked = f"treasure-{dialogue_id}"
            node_a.update_world(treasure_id=treasure_unlocked)
            node_b.update_world(treasure_id=treasure_unlocked)

        # 创建对话结果
        result = DialogueResult(
            dialogue_id=dialogue_id,
            participants=[node_a.node_id, node_b.node_id],
            input_context=input_context,
            emergence_score=emergence_score,
            new_insight=new_insight,
            new_world_state=new_world_state,
            treasure_unlocked=treasure_unlocked,
            dimension_scores=dimension_scores,
            cross_domain_insights=cross_domain_insights,
        )

        # 记录历史 (global + per-pair)
        self.dialogue_history.append(result)
        pair_key = self._pair_key(node_a.node_id, node_b.node_id)
        self._pair_history[pair_key].append(result)

        return result

    # ------------------------------------------------------------------
    # Emergence calculation
    # ------------------------------------------------------------------

    def _calculate_emergence(
        self,
        node_a: Node,
        node_b: Node,
        assessment_boost: float = 0.0,
    ) -> float:
        """
        计算涌现值

        The emergence score is a weighted combination of four factors:

        - **perspective_distance** (30%): Jaccard distance on character
          bigrams of the two nodes' perspective strings.
        - **knowledge_complementarity** (30%): Inverse Jaccard on word
          tokens of the knowledge bases, with a domain-coverage bonus.
        - **dialogue_depth** (20%): A multiplier that grows with the
          number of prior dialogues between the same pair.
        - **novelty_of_output** (20%): Baseline novelty (0.5), used as a
          placeholder for future output-analysis integration.

        An optional *assessment_boost* (0-0.15) is added on top when
        assessment data is available.

        Args:
            node_a: 节点A
            node_b: 节点B
            assessment_boost: Extra emergence from assessment complementarity.

        Returns:
            float: 涌现值 (0-1)
        """
        # 视角差异度 (continuous Jaccard)
        perspective_distance = self._perspective_distance(node_a, node_b)

        # 知识互补性 (continuous Jaccard + domain bonus)
        knowledge_complementarity = self._knowledge_complementarity(node_a, node_b)

        # 对话深度 — grows with repeated pair interactions
        dialogue_depth = self._dialogue_depth(node_a.node_id, node_b.node_id)

        # 输出新颖度（初始为0.5）
        novelty_of_output = 0.5

        # 综合计算
        emergence_score = (
            perspective_distance * 0.3
            + knowledge_complementarity * 0.3
            + dialogue_depth * 0.2
            + novelty_of_output * 0.2
            + assessment_boost
        )

        return min(max(emergence_score, 0.0), 1.0)

    # ------------------------------------------------------------------
    # Scoring primitives
    # ------------------------------------------------------------------

    def _perspective_distance(self, node_a: Node, node_b: Node) -> float:
        """Compute perspective distance using Jaccard distance on character bigrams.

        Returns a continuous score in [0, 1] where 0 means identical
        perspectives and 1 means completely different.
        """
        bigrams_a = _character_bigrams(node_a.seed["perspective"])
        bigrams_b = _character_bigrams(node_b.seed["perspective"])
        return _jaccard_distance(bigrams_a, bigrams_b)

    def _knowledge_complementarity(self, node_a: Node, node_b: Node) -> float:
        """Compute knowledge complementarity using Jaccard distance on word tokens.

        Higher values indicate *more complementary* (less overlapping)
        knowledge bases.  A bonus factor rewards pairs whose combined
        knowledge covers a broader set of domains (distinct tokens).

        Returns a continuous score in [0, 1].
        """
        tokens_a = _word_tokens(node_a.seed["knowledge_base"])
        tokens_b = _word_tokens(node_b.seed["knowledge_base"])

        # Base complementarity = Jaccard distance
        base = _jaccard_distance(tokens_a, tokens_b)

        # Domain-coverage bonus: more unique tokens in the union → richer
        # combined knowledge → higher bonus.  The bonus is capped at 0.15
        # and scales logarithmically with union size.
        union_size = len(tokens_a | tokens_b)
        if union_size > 0:
            # log2 grows slowly; 16 unique tokens -> bonus ~ 0.06
            bonus = min(0.15, math.log2(union_size + 1) * 0.02)
        else:
            bonus = 0.0

        return min(base + bonus, 1.0)

    def _dialogue_depth(self, node_a_id: str, node_b_id: str) -> float:
        """Compute dialogue depth multiplier for a node pair.

        ``dialogue_depth = 1.0 + min(0.3, len(pair_history) * 0.05)``

        The first dialogue between a pair yields depth 1.0.  Each
        subsequent dialogue adds 0.05 up to a maximum bonus of 0.3
        (i.e. 6 prior dialogues saturate the bonus).

        Returns:
            float in [1.0, 1.3].
        """
        pair_key = self._pair_key(node_a_id, node_b_id)
        history_len = len(self._pair_history.get(pair_key, []))
        return 1.0 + min(0.3, history_len * 0.05)

    # ------------------------------------------------------------------
    # Insight generation
    # ------------------------------------------------------------------

    def _generate_insight(
        self,
        node_a: Node,
        node_b: Node,
        emergence_score: float,
    ) -> Tuple[str, List[str]]:
        """Generate a rich insight string and cross-domain insight list.

        The insight mentions specific capability intersections between the
        two nodes and categorises the emergence score as high / medium / low.

        Args:
            node_a: 节点A
            node_b: 节点B
            emergence_score: 涌现值

        Returns:
            Tuple of (insight_text, cross_domain_insights).
        """
        # --- emergence category ---
        if emergence_score > 0.7:
            category = "high"
            category_zh = "高价值"
        elif emergence_score > 0.4:
            category = "medium"
            category_zh = "中等价值"
        else:
            category = "low"
            category_zh = "基础"

        # --- capability intersections ---
        caps_a = set(node_a.capabilities)
        caps_b = set(node_b.capabilities)
        shared_caps = sorted(caps_a & caps_b)
        unique_a = sorted(caps_a - caps_b)
        unique_b = sorted(caps_b - caps_a)

        intersection_parts: List[str] = []
        if shared_caps:
            intersection_parts.append(
                f"共同能力: {', '.join(shared_caps)}"
            )
        if unique_a and unique_b:
            intersection_parts.append(
                f"{node_a.name}独有[{', '.join(unique_a)}] "
                f"x {node_b.name}独有[{', '.join(unique_b)}]"
            )

        intersection_text = (
            "；".join(intersection_parts) if intersection_parts
            else "能力域无直接重叠"
        )

        # --- cross-domain insights ---
        cross_domain_insights: List[str] = []

        # Knowledge-domain based cross insights
        tokens_a = _word_tokens(node_a.seed["knowledge_base"])
        tokens_b = _word_tokens(node_b.seed["knowledge_base"])
        unique_domains_a = tokens_a - tokens_b
        unique_domains_b = tokens_b - tokens_a
        if unique_domains_a and unique_domains_b:
            cross_domain_insights.append(
                f"跨域交叉: {node_a.name}的[{', '.join(sorted(unique_domains_a)[:3])}] "
                f"与 {node_b.name}的[{', '.join(sorted(unique_domains_b)[:3])}] "
                f"形成互补知识桥"
            )

        if shared_caps and (unique_a or unique_b):
            cross_domain_insights.append(
                f"基于共享能力[{', '.join(shared_caps[:2])}]的"
                f"跨领域协作潜力"
            )

        # --- assemble insight ---
        insight = (
            f"[{category_zh}|{category}] "
            f"{node_a.name}的{node_a.seed['perspective']}视角 "
            f"与 {node_b.name}的{node_b.seed['perspective']}视角碰撞 "
            f"(涌现值={emergence_score:.2f})。"
            f"能力交叉: {intersection_text}。"
        )

        return insight, cross_domain_insights

    # ------------------------------------------------------------------
    # Assessment helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _load_node_profile(
        assessment_engine: Any,
        node_id: str,
    ) -> Optional[Dict[str, float]]:
        """Attempt to load the most recent dimension scores for *node_id*.

        Returns ``None`` if no history is available.
        """
        try:
            history = assessment_engine.load_history(node_id)
        except Exception:
            return None

        if not history:
            return None

        # Use the most recent assessment
        latest = history[-1]
        return dict(latest.profile.scores)

    @staticmethod
    def _profile_complementarity(
        profile_a: Dict[str, float],
        profile_b: Dict[str, float],
    ) -> float:
        """Measure how complementary two capability profiles are.

        For each shared dimension, compute the absolute difference.  The
        average difference across all dimensions is the complementarity
        score (0 = identical, 1 = maximally different).
        """
        all_dims = set(profile_a.keys()) | set(profile_b.keys())
        if not all_dims:
            return 0.0

        diffs: List[float] = []
        for dim in all_dims:
            sa = profile_a.get(dim, 0.0)
            sb = profile_b.get(dim, 0.0)
            diffs.append(abs(sa - sb))

        return sum(diffs) / len(diffs)

    # ------------------------------------------------------------------
    # Utilities
    # ------------------------------------------------------------------

    @staticmethod
    def _pair_key(id_a: str, id_b: str) -> Tuple[str, str]:
        """Return a canonical (sorted) pair key for two node IDs."""
        return tuple(sorted((id_a, id_b)))

    def get_pair_history(
        self,
        node_a_id: str,
        node_b_id: str,
    ) -> List[DialogueResult]:
        """Retrieve the dialogue history for a specific node pair.

        Args:
            node_a_id: First node ID.
            node_b_id: Second node ID.

        Returns:
            List of DialogueResult in chronological order.
        """
        pair_key = self._pair_key(node_a_id, node_b_id)
        return list(self._pair_history.get(pair_key, []))
